postgres:
  host: localhost
  port: 5432
  username: postgres
  password: 
  database: postgres

poloniex:
  key: YOUR_API_KEY
  secret: YOUR_API_SECRET

trading:
  fiat: BTC
  interval: 86400  # 1 day
